[package]
name = "git-commits-by-blob"
version = "1.0.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
publish = false

[dependencies]
git2 = "0.7.1"
failure = "0.1.1"
failure-tools = "4.0.2"
indicatif = "0.9.0"
bit-vec = "0.5.0"
